name: k6 Load Test
 
on:
  push:
    branches:
      - '**' # Here we can sepcify the branch name for granularity
 
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Setup  K6 and Run the test 
      - name: Setup K6
        uses: grafana/setup-k6-action@v1
      - name: Run local k6 test
        uses: grafana/run-k6-action@v1
        env:
          NGROK_URL: ${{ secrets.NGROK_URL }}
        with:
          path: test-api.js
      #     - name: Generate HTML report
      # - name: Upload report
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: k6-report
      #     path: k6-report.html